// Default data to use when API calls fail
import type { Country, Service, PaymentMethod } from "@/lib/types"

// Default countries with flags (70 countries)
export const defaultCountries: Country[] = [
  { id: 1, name: "United States", iso: "US", flag: "🇺🇸", available: true },
  { id: 2, name: "United Kingdom", iso: "GB", flag: "🇬🇧", available: true },
  { id: 3, name: "Russia", iso: "RU", flag: "🇷🇺", available: true },
  { id: 4, name: "Ukraine", iso: "UA", flag: "🇺🇦", available: true },
  { id: 5, name: "Kazakhstan", iso: "KZ", flag: "🇰🇿", available: true },
  { id: 6, name: "China", iso: "CN", flag: "🇨🇳", available: true },
  { id: 7, name: "Philippines", iso: "PH", flag: "🇵🇭", available: true },
  { id: 8, name: "Myanmar", iso: "MM", flag: "🇲🇲", available: true },
  { id: 9, name: "Indonesia", iso: "ID", flag: "🇮🇩", available: true },
  { id: 10, name: "Malaysia", iso: "MY", flag: "🇲🇾", available: true },
  { id: 11, name: "Vietnam", iso: "VN", flag: "🇻🇳", available: true },
  { id: 12, name: "Kyrgyzstan", iso: "KG", flag: "🇰🇬", available: true },
  { id: 13, name: "Israel", iso: "IL", flag: "🇮🇱", available: true },
  { id: 14, name: "Hong Kong", iso: "HK", flag: "🇭🇰", available: true },
  { id: 15, name: "Poland", iso: "PL", flag: "🇵🇱", available: true },
  { id: 16, name: "Romania", iso: "RO", flag: "🇷🇴", available: true },
  { id: 17, name: "Estonia", iso: "EE", flag: "🇪🇪", available: true },
  { id: 18, name: "Finland", iso: "FI", flag: "🇫🇮", available: true },
  { id: 19, name: "Latvia", iso: "LV", flag: "🇱🇻", available: true },
  { id: 20, name: "Lithuania", iso: "LT", flag: "🇱🇹", available: true },
  { id: 21, name: "Serbia", iso: "RS", flag: "🇷🇸", available: true },
  { id: 22, name: "Slovenia", iso: "SI", flag: "🇸🇮", available: true },
  { id: 23, name: "Slovakia", iso: "SK", flag: "🇸🇰", available: true },
  { id: 24, name: "Germany", iso: "DE", flag: "🇩🇪", available: true },
  { id: 25, name: "Italy", iso: "IT", flag: "🇮🇹", available: true },
  { id: 26, name: "Spain", iso: "ES", flag: "🇪🇸", available: true },
  { id: 27, name: "France", iso: "FR", flag: "🇫🇷", available: true },
  { id: 28, name: "Netherlands", iso: "NL", flag: "🇳🇱", available: true },
  { id: 29, name: "Sweden", iso: "SE", flag: "🇸🇪", available: true },
  { id: 30, name: "Portugal", iso: "PT", flag: "🇵🇹", available: true },
  { id: 31, name: "Brazil", iso: "BR", flag: "🇧🇷", available: true },
  { id: 32, name: "Colombia", iso: "CO", flag: "🇨🇴", available: true },
  { id: 33, name: "Mexico", iso: "MX", flag: "🇲🇽", available: true },
  { id: 34, name: "Peru", iso: "PE", flag: "🇵🇪", available: true },
  { id: 35, name: "Argentina", iso: "AR", flag: "🇦🇷", available: true },
  { id: 36, name: "Canada", iso: "CA", flag: "🇨🇦", available: true },
  { id: 37, name: "Australia", iso: "AU", flag: "🇦🇺", available: true },
  { id: 38, name: "New Zealand", iso: "NZ", flag: "🇳🇿", available: true },
  { id: 39, name: "India", iso: "IN", flag: "🇮🇳", available: true },
  { id: 40, name: "Pakistan", iso: "PK", flag: "🇵🇰", available: true },
  { id: 41, name: "Bangladesh", iso: "BD", flag: "🇧🇩", available: true },
  { id: 42, name: "Japan", iso: "JP", flag: "🇯🇵", available: true },
  { id: 43, name: "South Korea", iso: "KR", flag: "🇰🇷", available: true },
  { id: 44, name: "Thailand", iso: "TH", flag: "🇹🇭", available: true },
  { id: 45, name: "Egypt", iso: "EG", flag: "🇪🇬", available: true },
  { id: 46, name: "Morocco", iso: "MA", flag: "🇲🇦", available: true },
  { id: 47, name: "Kenya", iso: "KE", flag: "🇰🇪", available: true },
  { id: 48, name: "Nigeria", iso: "NG", flag: "🇳🇬", available: true },
  { id: 49, name: "South Africa", iso: "ZA", flag: "🇿🇦", available: true },
  { id: 50, name: "Turkey", iso: "TR", flag: "🇹🇷", available: true },
  { id: 51, name: "Greece", iso: "GR", flag: "🇬🇷", available: true },
  { id: 52, name: "Czech Republic", iso: "CZ", flag: "🇨🇿", available: true },
  { id: 53, name: "Hungary", iso: "HU", flag: "🇭🇺", available: true },
  { id: 54, name: "Austria", iso: "AT", flag: "🇦🇹", available: true },
  { id: 55, name: "Switzerland", iso: "CH", flag: "🇨🇭", available: true },
  { id: 56, name: "Belgium", iso: "BE", flag: "🇧🇪", available: true },
  { id: 57, name: "Denmark", iso: "DK", flag: "🇩🇰", available: true },
  { id: 58, name: "Norway", iso: "NO", flag: "🇳🇴", available: true },
  { id: 59, name: "Ireland", iso: "IE", flag: "🇮🇪", available: true },
  { id: 60, name: "Singapore", iso: "SG", flag: "🇸🇬", available: true },
  { id: 61, name: "Taiwan", iso: "TW", flag: "🇹🇼", available: true },
  { id: 62, name: "United Arab Emirates", iso: "AE", flag: "🇦🇪", available: true },
  { id: 63, name: "Saudi Arabia", iso: "SA", flag: "🇸🇦", available: true },
  { id: 64, name: "Qatar", iso: "QA", flag: "🇶🇦", available: true },
  { id: 65, name: "Kuwait", iso: "KW", flag: "🇰🇼", available: true },
  { id: 66, name: "Bahrain", iso: "BH", flag: "🇧🇭", available: true },
  { id: 67, name: "Oman", iso: "OM", flag: "🇴🇲", available: true },
  { id: 68, name: "Jordan", iso: "JO", flag: "🇯🇴", available: true },
  { id: 69, name: "Lebanon", iso: "LB", flag: "🇱🇧", available: true },
  { id: 70, name: "Iraq", iso: "IQ", flag: "🇮🇶", available: true },
]

// Default services with icons (100 services)
export const defaultServices: Service[] = [
  { id: 1, name: "WhatsApp", icon: "📱", description: "Verify your WhatsApp account", price: 4.0, available: true },
  { id: 2, name: "Telegram", icon: "✈️", description: "Verify your Telegram account", price: 4.0, available: true },
  { id: 3, name: "Facebook", icon: "👤", description: "Verify your Facebook account", price: 4.5, available: true },
  { id: 4, name: "Google", icon: "🔍", description: "Verify your Google account", price: 4.0, available: true },
  { id: 5, name: "Twitter", icon: "🐦", description: "Verify your Twitter account", price: 4.5, available: true },
  { id: 6, name: "Instagram", icon: "📷", description: "Verify your Instagram account", price: 5.0, available: true },
  { id: 7, name: "TikTok", icon: "🎵", description: "Verify your TikTok account", price: 5.5, available: true },
  { id: 8, name: "Snapchat", icon: "👻", description: "Verify your Snapchat account", price: 4.5, available: true },
  { id: 9, name: "LinkedIn", icon: "💼", description: "Verify your LinkedIn account", price: 4.0, available: true },
  { id: 10, name: "Uber", icon: "🚗", description: "Verify your Uber account", price: 4.5, available: true },
  { id: 11, name: "Airbnb", icon: "🏠", description: "Verify your Airbnb account", price: 5.0, available: true },
  { id: 12, name: "Netflix", icon: "🎬", description: "Verify your Netflix account", price: 5.5, available: true },
  { id: 13, name: "Amazon", icon: "📦", description: "Verify your Amazon account", price: 4.0, available: true },
  { id: 14, name: "PayPal", icon: "💰", description: "Verify your PayPal account", price: 6.0, available: true },
  { id: 15, name: "eBay", icon: "🛒", description: "Verify your eBay account", price: 4.5, available: true },
  { id: 16, name: "Tinder", icon: "❤️", description: "Verify your Tinder account", price: 5.0, available: true },
  { id: 17, name: "Bumble", icon: "🐝", description: "Verify your Bumble account", price: 5.0, available: true },
  { id: 18, name: "Discord", icon: "💬", description: "Verify your Discord account", price: 4.0, available: true },
  { id: 19, name: "Spotify", icon: "🎵", description: "Verify your Spotify account", price: 4.5, available: true },
  { id: 20, name: "Apple", icon: "🍎", description: "Verify your Apple account", price: 6.0, available: true },
  { id: 21, name: "Microsoft", icon: "💻", description: "Verify your Microsoft account", price: 5.0, available: true },
  { id: 22, name: "Steam", icon: "🎮", description: "Verify your Steam account", price: 4.5, available: true },
  {
    id: 23,
    name: "Epic Games",
    icon: "🎯",
    description: "Verify your Epic Games account",
    price: 4.5,
    available: true,
  },
  { id: 24, name: "Coinbase", icon: "💲", description: "Verify your Coinbase account", price: 6.5, available: true },
  { id: 25, name: "Binance", icon: "📊", description: "Verify your Binance account", price: 6.5, available: true },
  { id: 26, name: "Kraken", icon: "🐙", description: "Verify your Kraken account", price: 6.0, available: true },
  { id: 27, name: "Venmo", icon: "💸", description: "Verify your Venmo account", price: 5.0, available: true },
  { id: 28, name: "Cash App", icon: "💵", description: "Verify your Cash App account", price: 5.0, available: true },
  { id: 29, name: "Zelle", icon: "📲", description: "Verify your Zelle account", price: 5.5, available: true },
  { id: 30, name: "Skype", icon: "☁️", description: "Verify your Skype account", price: 4.0, available: true },
  { id: 31, name: "WeChat", icon: "💬", description: "Verify your WeChat account", price: 5.0, available: true },
  { id: 32, name: "Line", icon: "📱", description: "Verify your Line account", price: 4.5, available: true },
  { id: 33, name: "Viber", icon: "📞", description: "Verify your Viber account", price: 4.5, available: true },
  { id: 34, name: "KakaoTalk", icon: "🗣️", description: "Verify your KakaoTalk account", price: 4.5, available: true },
  { id: 35, name: "Signal", icon: "🔒", description: "Verify your Signal account", price: 5.0, available: true },
  { id: 36, name: "Threema", icon: "🔐", description: "Verify your Threema account", price: 5.0, available: true },
  { id: 37, name: "Twitch", icon: "🎮", description: "Verify your Twitch account", price: 4.5, available: true },
  { id: 38, name: "Reddit", icon: "👽", description: "Verify your Reddit account", price: 4.0, available: true },
  { id: 39, name: "Pinterest", icon: "📌", description: "Verify your Pinterest account", price: 4.0, available: true },
  { id: 40, name: "Tumblr", icon: "📝", description: "Verify your Tumblr account", price: 4.0, available: true },
  { id: 41, name: "Flickr", icon: "📸", description: "Verify your Flickr account", price: 4.0, available: true },
  { id: 42, name: "Vimeo", icon: "🎥", description: "Verify your Vimeo account", price: 4.5, available: true },
  { id: 43, name: "YouTube", icon: "▶️", description: "Verify your YouTube account", price: 5.0, available: true },
  { id: 44, name: "Vkontakte", icon: "🌐", description: "Verify your Vkontakte account", price: 4.5, available: true },
  {
    id: 45,
    name: "Odnoklassniki",
    icon: "👥",
    description: "Verify your Odnoklassniki account",
    price: 4.5,
    available: true,
  },
  { id: 46, name: "Badoo", icon: "💘", description: "Verify your Badoo account", price: 4.5, available: true },
  { id: 47, name: "Meetme", icon: "👋", description: "Verify your Meetme account", price: 4.5, available: true },
  { id: 48, name: "Hinge", icon: "💞", description: "Verify your Hinge account", price: 5.0, available: true },
  { id: 49, name: "OkCupid", icon: "💑", description: "Verify your OkCupid account", price: 5.0, available: true },
  { id: 50, name: "Grindr", icon: "👬", description: "Verify your Grindr account", price: 5.0, available: true },
  { id: 51, name: "Happn", icon: "👫", description: "Verify your Happn account", price: 5.0, available: true },
  { id: 52, name: "Tantan", icon: "💌", description: "Verify your Tantan account", price: 5.0, available: true },
  { id: 53, name: "Momo", icon: "👯", description: "Verify your Momo account", price: 5.0, available: true },
  { id: 54, name: "Blued", icon: "👨‍❤️‍👨", description: "Verify your Blued account", price: 5.0, available: true },
  { id: 55, name: "Taobao", icon: "🛍️", description: "Verify your Taobao account", price: 5.0, available: true },
  { id: 56, name: "Alibaba", icon: "🏪", description: "Verify your Alibaba account", price: 5.0, available: true },
  {
    id: 57,
    name: "AliExpress",
    icon: "🛒",
    description: "Verify your AliExpress account",
    price: 5.0,
    available: true,
  },
  { id: 58, name: "JD.com", icon: "🛒", description: "Verify your JD.com account", price: 5.0, available: true },
  { id: 59, name: "Pinduoduo", icon: "🛍️", description: "Verify your Pinduoduo account", price: 5.0, available: true },
  { id: 60, name: "Shopee", icon: "🛒", description: "Verify your Shopee account", price: 5.0, available: true },
  { id: 61, name: "Lazada", icon: "🛍️", description: "Verify your Lazada account", price: 5.0, available: true },
  {
    id: 62,
    name: "Mercado Libre",
    icon: "🛒",
    description: "Verify your Mercado Libre account",
    price: 5.0,
    available: true,
  },
  { id: 63, name: "OLX", icon: "🏪", description: "Verify your OLX account", price: 4.5, available: true },
  {
    id: 64,
    name: "Craigslist",
    icon: "📋",
    description: "Verify your Craigslist account",
    price: 4.5,
    available: true,
  },
  { id: 65, name: "Gumtree", icon: "🌳", description: "Verify your Gumtree account", price: 4.5, available: true },
  { id: 66, name: "Avito", icon: "📢", description: "Verify your Avito account", price: 4.5, available: true },
  { id: 67, name: "Leboncoin", icon: "🏷️", description: "Verify your Leboncoin account", price: 4.5, available: true },
  { id: 68, name: "Wallapop", icon: "🛍️", description: "Verify your Wallapop account", price: 4.5, available: true },
  { id: 69, name: "Fiverr", icon: "💼", description: "Verify your Fiverr account", price: 5.0, available: true },
  { id: 70, name: "Upwork", icon: "💻", description: "Verify your Upwork account", price: 5.0, available: true },
  {
    id: 71,
    name: "Freelancer",
    icon: "🔨",
    description: "Verify your Freelancer account",
    price: 5.0,
    available: true,
  },
  { id: 72, name: "Deliveroo", icon: "🍔", description: "Verify your Deliveroo account", price: 4.5, available: true },
  { id: 73, name: "UberEats", icon: "🍕", description: "Verify your UberEats account", price: 4.5, available: true },
  { id: 74, name: "DoorDash", icon: "🍲", description: "Verify your DoorDash account", price: 4.5, available: true },
  { id: 75, name: "GrubHub", icon: "🥡", description: "Verify your GrubHub account", price: 4.5, available: true },
  { id: 76, name: "Postmates", icon: "🛵", description: "Verify your Postmates account", price: 4.5, available: true },
  { id: 77, name: "Glovo", icon: "📦", description: "Verify your Glovo account", price: 4.5, available: true },
  { id: 78, name: "Bolt", icon: "🚖", description: "Verify your Bolt account", price: 4.5, available: true },
  { id: 79, name: "Lyft", icon: "🚗", description: "Verify your Lyft account", price: 4.5, available: true },
  { id: 80, name: "Grab", icon: "🚕", description: "Verify your Grab account", price: 4.5, available: true },
  { id: 81, name: "DiDi", icon: "🚘", description: "Verify your DiDi account", price: 4.5, available: true },
  { id: 82, name: "Careem", icon: "🚖", description: "Verify your Careem account", price: 4.5, available: true },
  { id: 83, name: "Gojek", icon: "🛵", description: "Verify your Gojek account", price: 4.5, available: true },
  {
    id: 84,
    name: "Booking.com",
    icon: "🏨",
    description: "Verify your Booking.com account",
    price: 5.0,
    available: true,
  },
  { id: 85, name: "Expedia", icon: "✈️", description: "Verify your Expedia account", price: 5.0, available: true },
  {
    id: 86,
    name: "Hotels.com",
    icon: "🏢",
    description: "Verify your Hotels.com account",
    price: 5.0,
    available: true,
  },
  { id: 87, name: "Agoda", icon: "🏩", description: "Verify your Agoda account", price: 5.0, available: true },
  { id: 88, name: "Ctrip", icon: "🧳", description: "Verify your Ctrip account", price: 5.0, available: true },
  { id: 89, name: "Klarna", icon: "💳", description: "Verify your Klarna account", price: 5.5, available: true },
  { id: 90, name: "Revolut", icon: "💱", description: "Verify your Revolut account", price: 5.5, available: true },
  { id: 91, name: "Wise", icon: "💸", description: "Verify your Wise account", price: 5.5, available: true },
  { id: 92, name: "N26", icon: "🏦", description: "Verify your N26 account", price: 5.5, available: true },
  { id: 93, name: "Monzo", icon: "💰", description: "Verify your Monzo account", price: 5.5, available: true },
  { id: 94, name: "Starling", icon: "🏛️", description: "Verify your Starling account", price: 5.5, available: true },
  { id: 95, name: "Curve", icon: "💳", description: "Verify your Curve account", price: 5.5, available: true },
  { id: 96, name: "Robinhood", icon: "📈", description: "Verify your Robinhood account", price: 6.0, available: true },
  { id: 97, name: "eToro", icon: "📊", description: "Verify your eToro account", price: 6.0, available: true },
  {
    id: 98,
    name: "Trading212",
    icon: "📉",
    description: "Verify your Trading212 account",
    price: 6.0,
    available: true,
  },
  { id: 99, name: "Plus500", icon: "💹", description: "Verify your Plus500 account", price: 6.0, available: true },
  { id: 100, name: "Webull", icon: "📊", description: "Verify your Webull account", price: 6.0, available: true },
]

// Default payment methods
export const defaultPaymentMethods: PaymentMethod[] = [
  { id: 1, name: "Cryptomus", icon: "🪙", available: true },
  { id: 2, name: "PayPal", icon: "💳", available: true },
  { id: 3, name: "M-Pesa", icon: "📱", available: true },
]

// Support contact information
export const supportContacts = {
  phone: "+254727750097",
  whatsapp: "+254740712869",
  telegram: "AstroVerse",
}
